import Head from 'next/head';
import "../../public/assets/css/plugins/fontawesome-6.css";
import "../../public/assets/css/plugins/swiper.min.css";
import "../../public/assets/css/vendor/magnific-popup.css";
import "../../public/assets/css/vendor/bootstrap.min.css";
import "../../public/assets/css/vendor/metismenu.css";
import "../../public/assets/css/style.css";
import 'react-modal-video/css/modal-video.min.css';
import 'aos/dist/aos.css';
import Script from 'next/script';


export const metadata = {
  title: "Innovat Architecture NextJs Template",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/fav.png", // Ensure the path is correct
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Innovat Architecture NextJs Template</title>
        <meta name="author" content="themewant" />
        <meta name="description" content="Innovat Architecture NextJs Template" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/fav.png" />
      </Head>
      <body className='index-one'>

        {children}



        <Script
          src="/assets/js/plugins/smoothscroll.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
